# Generated by Django 5.0.4 on 2024-05-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_empoyee_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dep',
            new_name='dept',
        ),
    ]
